server:
  port: 8100
spring:
  application:
    name: currency-conversion

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true    
  service-url:
    defaultzone: http://localhost:8761/eureka/
  

